# Generated by Django 5.2.5 on 2025-09-18 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GymSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gym_name",
                    models.CharField(default="FitLife Wellness Center", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(default="info@fitlifegym.com", max_length=254),
                ),
                ("phone", models.CharField(default="(555) 123-4567", max_length=20)),
                ("address", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("timezone", models.CharField(default="est", max_length=50)),
                ("currency", models.CharField(default="usd", max_length=10)),
                ("date_format", models.CharField(default="mdy", max_length=20)),
                ("language", models.CharField(default="en", max_length=10)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=True)),
                ("two_factor", models.BooleanField(default=False)),
                ("auto_backup", models.BooleanField(default=True)),
                ("primary_color", models.CharField(default="#6366f1", max_length=7)),
                ("secondary_color", models.CharField(default="#f1f5f9", max_length=7)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
            ],
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("features", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("join_date", models.DateField()),
                ("last_visit", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership_plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gymnast.membershipplan",
                    ),
                ),
            ],
        ),
    ]
