# Generated by Django 5.2.5 on 2025-09-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gymnast", "0002_class_member_address_member_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
