# Generated by Django 5.2.5 on 2025-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymnast', '0003_member_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='member',
            name='face_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
