# Generated by Django 5.2.5 on 2025-09-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
